version: "3.7"
services:
  go-template:
    build: .devcontainer
    tty: true
    volumes:
      - ./:/src/:delegated
    networks:
      - organization-service
networks:
  organization-service:
    external: true
