// This file was generated by goorg/cli/repository at 2021/02/01 11:50:04

package repositories

import (
	"context"
)

type (
	Repository interface {
		NewConnection() (Connection, error)
		MustConnection() Connection
	}
	Connection interface {
		Transaction(c context.Context, f func(tx Transaction) error) error
	}
	Transaction interface {
	}
)
