// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by goorg/di/generator at 2021/01/31 21:53:10

package register

import (
	"github.com/organization-service/goorg/di"
	"github.com/organization-service/goorg/internal/examples/infra"
	"github.com/organization-service/goorg/internal/examples/usecase"
)

func New() *di.Container {
	container := di.New()
	container.Provide(infra.NewRepository)
	container.Provide(usecase.NewUseCase)

	return container
}
