// This file was generated by goorg/cli/swagger at 2021/05/01 15:43:15

package server

import "github.com/savaki/swag/swagger"

type (
	swaggerWrap struct {
		tag       swagger.Tag
		endpoints []*swagger.Endpoint
	}
	swaggerWraps struct {
		values []*swaggerWrap
	}
)

func NewSwaggerSrv() *swaggerWrap {
	return &swaggerWrap{
		tag:       swagger.Tag{},
		endpoints: make([]*swagger.Endpoint, 0),
	}
}

func (s *swaggerWrap) AddEndpoint(endpint *swagger.Endpoint) {
	s.endpoints = append(s.endpoints, endpint)
}

func (s *swaggerWraps) AddServer(srv *swaggerWrap) {
	s.values = append(s.values, srv)
}

func (s *swaggerWraps) Endpoints() []*swagger.Endpoint {
	endpoints := []*swagger.Endpoint{}
	for _, srv := range s.values {
		for _, ep := range srv.endpoints {
			endpoints = append(endpoints, ep)
		}
	}
	return endpoints
}

func (s *swaggerWraps) Tags() []swagger.Tag {
	tags := []swagger.Tag{}
	for _, srv := range s.values {
		tags = append(tags, srv.tag)
	}
	return tags
}
