name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Cache
        uses: actions/cache@v2.1.0
        if: ${{ !env.ACT }}
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  release:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: version outputs
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo $VERSION
          echo '::set-output name=VERSION::${VERSION}'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
