// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by goorg/di/generator at {{ .Timestamp }}

package {{.PackageName}}

import (

	"github.com/organization-service/goorg/v2/database"
	"github.com/organization-service/goorg/v2/di"
)

var container *di.Container

func New() *di.Container {
	if container == nil {
		container = di.New()
		{{- if .DriverInclude }}
		container.Provide(database.New)
		{{- end}}
		{{- range .Definitions}}
		{{- if ne .FuncName ""}}
		container.Provide({{.FuncName}})
		{{- end}}
		{{- end}}
	}
	return container
}